[package]
name = "bn_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["fs"] }
axum = "0.7.5"
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
pvpgn-hash-rs = "1.0.0"
rand = "0.8.5"
config = "0.14.0"
log = "0.4.21"